development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: asdbot_production
  username: asdbot
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5
  timeout: 5000
